homepage/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('story8', views.story8, name='story8'),
    path('accounts/profile/', views.userpage, name='userpage'),
    path('loginpage', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logoutpage', views.logout_view, name='logout')
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    # path('story8/', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Status(models.Model):
    # Fields
    status_field = models.TextField(max_length=300)
    date_field = models.DateTimeField(auto_now=True)

homepage/forms.py
from django import forms
from .models import Status


class UserModelForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'

homepage/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import UserModelForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# Create your views here.

def index(request):
    stat = Status.objects.all(); 
    context = {}
    if request.method == 'POST':        
        form = UserModelForm(request.POST or None)
        if form.is_valid():
            form.save()
            form = UserModelForm()
            return HttpResponseRedirect('/')
    else:
        form = UserModelForm()

    return render(request, 'index.html',{'form': form,"stat":stat})

def story8(request):
    return render(request, 'story8.html')

@login_required(login_url='/loginpage')
def userpage(request):
    return render(request, 'userpage.html')

def logout_view(request):
    logout(request)
    return redirect('homepage:index')

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Mario E</title>
    <link rel="stylesheet" href="{% static 'css/story.css' %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <link
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'jquery/story.js' %}"></script>
  </head>
  <body id="temaA">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Mario Ekaputta</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarText"
        aria-controls="navbarText"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:login' %}">Login</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'homepage:story8' %}"
              >Story 8 <span class="sr-only">(current)</span></a
            >
          </li>
        </ul>
        <span class="navbar-text">
          PPW
        </span>
      </div>
    </nav>
    <main>
      {% block content %} {% endblock %}
    </main>
  </body>
</html>

homepage/templates/index.html
{% extends 'base.html' %}
{% block content %}

  <button id="gantitema">Ganti Tema</button>
<!--   <div class="temaA" id="divYangMauDiubah"> kosong </div> -->

  <div class="demo temaA" id="divYangMauDiubah">
    <h3>Aktivitas</h3>
    <div>
    Kuliah</br>Makan</br>Refreshing</br>Tidur</br>Repeat
    </div>
    <h3>Pengalaman Organisasi/Kepanitiaan</h3>
    <div>
    Staf Permainan Sospro Fasilkom UI 2018</br>Staf Perlengkapan Pemira Fasilkom UI 2018</br>Staf LO Wisuda Ganjil Fasilkom UI 2018</br>Staf Startup Academy Compfest XI</br>PJ LO Wisuda Genap Fasilkom UI 2019
    </div>
    <h3>Prestasi</h3>
    <div>
    Juara 2 SEC Business Competition Universitas Brawijaya</br>
    Juara 1 Hilo Marketing Strategy Competition
    </div>
  </div>

<h1>Halo Apa Kabar?</h1>

<div class="status"style="margin-top:20px">
     <form method='POST' > 
        {% csrf_token %}
                {{ form.as_p }}
                <input name='simpan' type='submit' value='Save' />
            </form>
</div>

<div id="section2" style="height: auto">
  <p>Ini Statusku</p>
        <ol>
          {% for i in stat %}
            <li>status : {{i.status_field}}
              date : {{i.date_field}}
            </li>
           {% endfor %}
        </ol>
    </div>
{% endblock %}

homepage/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container" id="logincontainer">
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %} {% if next %} {% if user.is_authenticated %}
            <p>
              Your account doesn't have access to this page. To proceed, please login
              with an account that has access.
            </p>
            {% else %}
            <p>Please login to see this page.</p>
            {% endif %} {% endif %}
        
            <form method="post" action="{% url 'homepage:login' %}">
              {% csrf_token %}
<div class="form-group">
        {{ form.username.label_tag }}
        {{ form.username }}
</div>
<div class="form-group">
        {{ form.password.label_tag }}
        {{ form.password }}
</div>
                  <!-- <td>{{ form.username.label_tag }}</td>
                  <td>{{ form.username }}</td>
                </tr>
                <tr>
                  <td>{{ form.password.label_tag }}</td>
                  <td>{{ form.password }}</td>
                </tr>
              </table> -->
        
              <input type="submit" class="btn btn-primary" value="login" />
              <input type="hidden" name="next" value="{{ next }}" />
            </form>
    </div>
{% endblock %}

homepage/templates/story8.html
<!doctype html>
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<title>Mario E</title>
<link rel="stylesheet" href="{% static 'css/story.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<script src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static 'jquery/story8.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Mario Ekaputta</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Story 8 <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <span class="navbar-text">
      PPW
    </span>
  </div>
</nav>
<main>
    <div class="d-flex justify-content-center align-items-center container">
      <form id="f">
  <div class="input-group">
    <input type="text" class="form-control" placeholder="Search Books" value="Harry Potter" id="search">
    <div class="input-group-append">
      <button class="btn btn-secondary" type="button">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>
</form>
</div>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Author</th>                
                <th scope="col">Publisher</th>
                <th scope="col">Image</th>
            </tr>
        </thead>
        <tbody id="cont">
        </tbody>
    </table>
</div>
</main>
<script type="text/javascript" src="{% static 'jquery/story8.js' %}"></script>
</body>
</html>

homepage/templates/userpage.html
{% extends "base.html" %}
{% block content %}
<p>Welcome, {{ user.username }} ({{ user.first_name}} {{ user.last_name}}). Thanks for logging in.</p>
<a href="{% url 'homepage:logout' %}">Logout</a>
{% endblock %}